const carForm = document.querySelector("div.car-details form#car-form")
const carNameInput = document.querySelector("form#car-form textarea#car-name")
const carDescriptionInput = document.querySelector("form#car-form textarea#car-description")
const carImgInput = document.querySelector("form#car-form textarea#car-image")
const carPrice8Input = document.querySelector("form#car-form textarea#car-price8")
const carPrice24Input = document.querySelector("form#car-form textarea#car-price24")
const usernameInput = document.querySelector("form#car-form textarea#username")